name: Test Dynamic Hedge Module

on:
  push:
    branches: [ feature/phase-1.5-dynamic-hedge ]
  pull_request:
    branches: [ master, main ]
    paths:
      - 'dynamic_hedge/**'
      - 'tests/test_dynamic_hedge/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio scipy numpy pandas
        
    - name: Run Dynamic Hedge Tests
      run: |
        pytest tests/test_dynamic_hedge/ -v